kind: Pod
apiVersion: v1
metadata:
  name: flex-provisioner
spec:
  containers:
    - name: flex-provisioner
      image: childsb/flex-provisioner
      securityContext:
      args:
        - "-provisioner=external/flex-simple"
        - "-execCommand=/opt/go/src/github.com/childsb/flex-provisioner/flex/flex/flex"
      imagePullPolicy: "IfNotPresent"

