kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-drbd
  annotations:
    volume.beta.kubernetes.io/storage-class: two-replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
